[package]
name = "chat-svc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0.0", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["full"] } 
tokio-stream = { version = "0.1" }

futures = { version = "0.3.0", features = ["thread-pool"]}

# debug
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
